name: iptvscanner

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - name: System update
      run: |
        sudo -E apt-mark hold grub-efi-amd64-signed
        sudo -E apt -y update --allow-unauthenticated
        sudo -E apt -y full-upgrade
        sudo -E systemctl daemon-reload
        sudo apt-get autoremove -y --purge
        sudo apt-get clean

    - name: Set Timezone
      run: |
        sudo timedatectl set-timezone Asia/Shanghai

    - uses: actions/checkout@main

    - name: Install latest Go
      uses: actions/setup-go@main
      with:
        go-version: 'stable'
        check-latest: true

    - name: Install latest UPX
      run: |
        UPX_VERSION=$(curl --silent "https://api.github.com/repos/upx/upx/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
        curl -L -o upx.tar.xz "https://github.com/upx/upx/releases/download/v${UPX_VERSION}/upx-${UPX_VERSION}-amd64_linux.tar.xz"
        tar -xf upx.tar.xz
        sudo mv upx-${UPX_VERSION}-amd64_linux/upx /usr/local/bin

    - name: Build and Compress
      run: |
        go mod init iptvscanner
        go get -u ./...
        go mod tidy
        go mod download
        CGO_ENABLED=0 GOOS="windows" GOARCH="amd64" GOAMD64=v2 go build -trimpath -buildvcs=false -gcflags="all=-l=4" -ldflags "-s -w -buildid=" -o iptvscanner.exe iptvscanner.go
        upx --lzma --best iptvscanner.exe
        zip -j -9 iptvscanner_win64_qwerttvv.zip iptvscanner.exe

    - name: push
      uses: EndBug/add-and-commit@main
      with:
        default_author: github_actions
        message: "iptvscanner update by qwerttvv"
        add: "iptvscanner_win64_qwerttvv.zip"
